local yarns1_5 = {
	layouts = {
		{abbreviation = "1M", parts = 1},
		{abbreviation = "2M", parts = 2},
		{abbreviation = "4M", parts = 4},
		{abbreviation = "2P", parts = 1},
		{abbreviation = "4P", parts = 1},
		{abbreviation = "2>", parts = 1},
		{abbreviation = "4>", parts = 1},
		{abbreviation = "8>", parts = 1},
		{abbreviation = "4T", parts = 4},
		{abbreviation = "4V", parts = 2},
		{abbreviation = "3+", parts = 2},
	},
    rc = {
		[1] = { id = "layout", abbreviation="LA", custom=true},
		[2] = { id = "tempo" },
		[3] = { id = "swing" },
		[33] = { id = "inputClockDiv", abbreviation="I/"},
		[34] = { id = "outputClockDiv", abbreviation="O/"},
		[35] = { id = "barDuration", abbreviation="B-"},
		[65] = { id = "nudgeFirstTick", abbreviation="NU"},
		[66] = { id = "clockManualStart", abbreviation="MS" },
		[67] = { id = "clockOutput", abbreviation="C>" },
    },
	partOffsets = {4, 36, 68, 100},
    partrc = {
		{id="midiChannel", abbreviation="CH"},
		{id="lowerNote", abbreviation="N<"},
		{id="upperNote", abbreviation="N>"},
		{id="voicing", abbreviation="VO"},
		{id="notePriority", abbreviation="NP"},
		{id="portamento", abbreviation="PO"},
		{id="legatoMode", abbreviation="LG"},
		{id="pitchBendRange", abbreviation="BR"},
		{id="vibratoRange", abbreviation="VR"},
		{id="vibratoSpeed", abbreviation="VS"},
		{id="transpose", abbreviation="TT"},
		{id="fineTune", abbreviation="TF"},
		{id="tuningRoot", abbreviation="TR"},
		{id="tuningSystem", abbreviation="TS"},
		{id="triggerDuration", abbreviation="T-"},
		{id="triggerVelocityScale", abbreviation="T*"},
		{id="triggerShape", abbreviation="T|\\"},
		{id="auxOut", abbreviation=">"},
		{id="oscWaveform", abbreviation="OS"},
		{id="arpSeqClockDivision", abbreviation="C/"},
		{id="arpSeqGateLength", abbreviation="G-"},
		{id="arpRange", abbreviation="AR"},
		{id="arpDirection", abbreviation="AD/RG"},
		{id="arpPattern", abbreviation="AD/RP"},
		{id="euclidianLength", abbreviation="E-"},
		{id="euclidianFill", abbreviation="EF"},
		{id="euclidianRotate", abbreviation="ER"},
    },
    partcc = {
		[1] = {id="vibrato"},
		[2] = {id="aux1"},
		[4] = {id="aux2"},
		[5] = {id="portamento", abbreviation="PO"},

		[16] = {id="lowerNote", abbreviation="N<"},
		[17] = {id="upperNote", abbreviation="N>"},
		[18] = {id="voicing", abbreviation="VO"},
		[19] = {id="notePriority", abbreviation="NP"},
		[20] = {id="legatoMode", abbreviation="LG"},
		[21] = {id="pitchBendRange", abbreviation="BR"},
		[22] = {id="vibratoRange", abbreviation="VR"},
		[23] = {id="vibratoSpeed", abbreviation="VS"},
		[24] = {id="transpose", abbreviation="TT"},
		[25] = {id="fineTune", abbreviation="TF"},
		[26] = {id="tuningRoot", abbreviation="TR"},
		[27] = {id="tuningSystem", abbreviation="TS"},
		[28] = {id="triggerDuration", abbreviation="T-"},
		[29] = {id="triggerVelocityScale", abbreviation="T*"},
		[30] = {id="triggerShape", abbreviation="T|\\"},
		[31] = {id="auxOut3", abbreviation="3>"},

		[71] = {id="oscWaveform", abbreviation="OS"},
		[72] = {id="auxOut4", abbreviation="4>"},
		[73] = {id="tuningFactor", abbreviation="T*"},

		[102] = {id="arpSeqClockDivision", abbreviation="C/"},
		[103] = {id="arpSeqGateLength", abbreviation="G-"},
		[104] = {id="arpRange", abbreviation="AR"},
		[105] = {id="arpDirection", abbreviation="AD/RG"},
		[106] = {id="arpPattern", abbreviation="AD/RP"},
		[107] = {id="euclidianLength", abbreviation="E-"},
		[108] = {id="euclidianFill", abbreviation="EF"},
		[109] = {id="euclidianRotate", abbreviation="ER"},
		[112] = {id="recordTie", abbreviation="ER"},
		[113] = {id="recordReset", abbreviation="ER"},
    }
}

local loom2_3 = {
	layouts = {
		{abbreviation = "1M", parts = 1},
		{abbreviation = "2M", parts = 2},
		{abbreviation = "4M", parts = 4},
		{abbreviation = "2P", parts = 1},
		{abbreviation = "4P", parts = 1},
		{abbreviation = "2>", parts = 1},
		{abbreviation = "4>", parts = 1},
		{abbreviation = "8>", parts = 1},
		{abbreviation = "4T", parts = 4},
		{abbreviation = "4V", parts = 2},
		{abbreviation = "3+", parts = 2},
		{abbreviation = "2+2", parts = 3},
		{abbreviation = "2+1", parts = 2},
		{abbreviation = "*2", parts = 2},
		{abbreviation = "3M", parts = 3},
	},
    rc = {
		[0] = { id = "outputClockRatio", abbreviation="O/"},
		[1] = { id = "layout", abbreviation="LA", custom=true},
		[2] = { id = "tempo" },
		[3] = { id = "swing" },
    },
	partOffsets = {4, 36, 68, 100},
    partrc = {
		{id="midiChannel", abbreviation="CH"},
		{id="lowerNote", abbreviation="N<"},
		{id="upperNote", abbreviation="N>"},
		{id="midiOutMode"},
		{id="voicing", abbreviation="VO"},
		{id="notePriority", abbreviation="NP"},
		{id="portamento", abbreviation="PO"},
		{id="legatoMode", abbreviation="LG"},
		{id="pitchBendRange", abbreviation="BR"},
		{id="vibratoRange", abbreviation="VR"},
		{id="vibratoSpeed", abbreviation="VS"},
		{id="transpose", abbreviation="TT"},
		{id="fineTune", abbreviation="TF"},
		{id="tuningRoot", abbreviation="TR"},
		{id="tuningSystem", abbreviation="TS"},
		{id="triggerDuration", abbreviation="T-"},
		{id="triggerVelocityScale", abbreviation="T*"},
		{id="triggerShape", abbreviation="T|\\"},
		{id="auxOut", abbreviation=">"},
		{id="oscWaveform", abbreviation="OS"},
		{id="arpSeqClockDivision", abbreviation="C/"},
		{id="arpSeqGateLength", abbreviation="G-"},
		{id="arpRange", abbreviation="AR"},
		{id="arpDirection", abbreviation="AD/RG"},
		{id="arpPattern", abbreviation="AD/RP"},
		{id="euclidianLength", abbreviation="E-"},
		{id="euclidianFill", abbreviation="EF"},
		{id="euclidianRotate", abbreviation="ER"},
    },
    partcc = {
		[1] = {id="vibrato"},
		[2] = {id="aux1"},
		[4] = {id="aux2"},
		[5] = {id="portamento", abbreviation="PO"},

		[16] = {id="lowerNote", abbreviation="N<"},
		[17] = {id="upperNote", abbreviation="N>"},
		[18] = {id="voicing", abbreviation="VO"},
		[19] = {id="notePriority", abbreviation="NP"},
		[20] = {id="legatoMode", abbreviation="LG"},
		[21] = {id="pitchBendRange", abbreviation="BR"},
		[22] = {id="vibratoRange", abbreviation="VR"},
		[23] = {id="vibratoSpeed", abbreviation="VS"},
		[24] = {id="transpose", abbreviation="TT"},
		[25] = {id="fineTune", abbreviation="TF"},
		[26] = {id="tuningRoot", abbreviation="TR"},
		[27] = {id="tuningSystem", abbreviation="TS"},
		[28] = {id="triggerDuration", abbreviation="T-"},
		[29] = {id="triggerVelocityScale", abbreviation="T*"},
		[30] = {id="triggerShape", abbreviation="T|\\"},
		[31] = {id="auxOut3", abbreviation="3>"},
		[32] = {id="portamentoLegatoOnly"},

		[70] = {id="oscMode", abbreviation="OS"},
		[71] = {id="oscWaveform", abbreviation="OS"},
		[72] = {id="auxOut4", abbreviation="4>"},
		[73] = {id="transposeOctave"},
		[74] = {id="holdPedalMode"},
		[75] = {id="seqMode"},
		[76] = {id="seqInputResponse"},
		[77] = {id="envAttack"},
		[78] = {id="envDecay"},
		[79] = {id="envSustain"},
		[80] = {id="envRelease"},
		[81] = {id="oscTimbreLfoShape"},
		[82] = {id="oscTimbreInit"},
		[83] = {id="oscTimbreLfoMod"},
		[84] = {id="loopLength"},
		[85] = {id="holdPedalPolarity"},
		[86] = {id="envAttackMod"},
		[87] = {id="envDecayMod"},
		[88] = {id="envSustainMod"},
		[89] = {id="envReleaseMod"},
		[90] = {id="oscTimbreEnvModInit"},
		[91] = {id="oscTimbreEnvModLfoMod"},
		[92] = {id="envPeak"},
		[93] = {id="tremoloDepth"},
		[94] = {id="tremoloShape"},
		[95] = {id="vibratoShape"},

		[102] = {id="arpSeqClockDivision", abbreviation="C/"},
		[103] = {id="arpSeqGateLength", abbreviation="G-"},
		[104] = {id="arpRange", abbreviation="AR"},
		[105] = {id="arpDirection", abbreviation="AD/RG"},
		[106] = {id="arpPattern", abbreviation="AD/RP"},
		[107] = {id="euclidianLength", abbreviation="E-"},
		[108] = {id="euclidianFill", abbreviation="EF"},
		[109] = {id="euclidianRotate", abbreviation="ER"},
		[110] = {id="seqRecord"},
		[111] = {id="seqDelete"},
		[112] = {id="recordTie"},
		[113] = {id="recordReset"},
		[114] = {id="arpSeqPlayMode"},
		[115] = {id="loopPhaseOffset"},
		[116] = {id="macroRecordingMode"},
		[117] = {id="macroPlayMode"},
		[118] = {id="lfoSpreadTypes"},
		[119] = {id="lfoSpreadVoices"},
    }

}

return {yarns=yarns1_5, loom=loom2_3}
